apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kodiak
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kodiak
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: kodiak
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: kodiak
    spec:
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: controller:0.2.0
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --tailscale-image=tailscale/tailscale:v1.98.9
          env:
            - name: IONSCALE_API_ENDPOINT
              value: ""
            - name: IONSCALE_LOGIN_URL
              value: ""
            - name: IONSCALE_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: ionscale-admin
                  key: systemAdminKey
                  optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
