resources:
  - service_account.yaml
  - role.yaml
  - role_binding.yaml
  - leader_election_role.yaml
  - leader_election_role_binding.yaml
  - metrics_auth_role.yaml
  - metrics_auth_role_binding.yaml
  - metrics_reader_role.yaml
  - connector_admin_role.yaml
  - connector_editor_role.yaml
  - connector_viewer_role.yaml
  - authkey_admin_role.yaml
  - authkey_editor_role.yaml
  - authkey_viewer_role.yaml
  - tailnet_admin_role.yaml
  - tailnet_editor_role.yaml
  - tailnet_viewer_role.yaml
