---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kodiak.mnicloud.jp
  resources:
  - authkeys
  - connectorinstances
  - connectors
  - tailnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kodiak.mnicloud.jp
  resources:
  - authkeys/finalizers
  - connectorinstances/finalizers
  - connectors/finalizers
  - tailnets/finalizers
  verbs:
  - update
- apiGroups:
  - kodiak.mnicloud.jp
  resources:
  - authkeys/status
  - connectorinstances/status
  - connectors/status
  - tailnets/status
  verbs:
  - get
  - patch
  - update
