apiVersion: kodiak.mnicloud.jp/v1alpha1
kind: Tailnet
metadata:
  name: quickstart-tailnet
spec:
  name: quickstart
  aclPolicy: |
    {
      "acls": [
        {
          "action": "accept",
          "src": ["*"],
          "dst": ["*:*"]
        }
      ],
      "autoApprovers": {
        "routes": {
          "10.244.0.0/16": ["tag:k8s"],
          "10.96.0.0/12": ["tag:k8s"]
        }
      }
    }
---
apiVersion: kodiak.mnicloud.jp/v1alpha1
kind: Connector
metadata:
  name: quickstart-connector
spec:
  tailnetRef:
    name: quickstart-tailnet
  tags:
    - tag:k8s
  subnetRouter:
    advertiseRoutes:
      - 10.244.0.0/16
      - 10.96.0.0/12
