apiVersion: kodiak.mnicloud.jp/v1alpha1
kind: Tailnet
metadata:
  labels:
    app.kubernetes.io/name: kodiak
    app.kubernetes.io/managed-by: kustomize
  name: tailnet-sample
spec:
  controlServerRef:
    name: controlserver-sample
  name: "my-tailnet"
  iamPolicy: |
    {
      "groups": {
        "group:admin": ["user@example.com"]
      }
    }
  aclPolicy: |
    {
      "groups": {
        "group:admin": ["user@example.com"]
      },
      "acls": [
        {
          "action": "accept",
          "src": ["*"],
          "dst": ["*:*"]
        }
      ]
    }
  dnsConfig:
    magicDns: true
    nameservers:
      - "8.8.8.8"
      - "8.8.4.4"
  serviceCollectionEnabled: false
  fileSharingEnabled: true
  sshEnabled: true
  machineAuthorizationEnabled: false
