apiVersion: kodiak.mnicloud.jp/v1alpha1
kind: Connector
metadata:
  name: connector-sample
spec:
  tailnetRef:
    name: tailnet-sample
  tags:
    - tag:k8s
  subnetRouter:
    advertiseRoutes:
      - 10.244.0.0/16
      - 10.96.0.0/12
  workload:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
