apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# SQLite overlay for ionscale
# Uses PersistentVolumeClaim for data storage

namespace: kodiak-system

resources:
- ../../base
- pvc.yaml

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: ionscale

configMapGenerator:
- name: ionscale-config
  files:
  - config.yaml
  options:
    disableNameSuffixHash: true
