apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ionscale-data
spec:
  # Change storageClassName for your environment
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
