apiVersion: apps/v1
kind: Deployment
metadata:
  name: ionscale
  labels:
    app.kubernetes.io/name: ionscale
    app.kubernetes.io/component: control-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ionscale
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ionscale
    spec:
      containers:
      - name: ionscale
        image: ghcr.io/jsiebens/ionscale:0.15.0
        args:
        - server
        - --config
        - /etc/ionscale/config.yaml
        ports:
        - name: api
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 9091
          protocol: TCP
        - name: stun
          containerPort: 3478
          protocol: UDP
        env:
        - name: IONSCALE_KEYS_SYSTEM_ADMIN_KEY
          valueFrom:
            secretKeyRef:
              name: ionscale-admin
              key: systemAdminKey
        volumeMounts:
        - name: config
          mountPath: /etc/ionscale
          readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /version
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /version
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: ionscale-config
